apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mc
  name: mc
spec:
  selector:
    matchLabels:
      app: mc
  serviceName: mc
  replicas: 1
  template:
    metadata:
      labels:
        app: mc
    spec:
      imagePullSecrets:
        - name: ghcr
      securityContext:
        runAsUser: 61000
        runAsGroup: 61000
        fsGroup: 61000
      containers:
        - name: mc
          image: ghcr.io/unatoon/minecraft-server:1
          ports:
            - containerPort: 25565
              name: mc
          volumeMounts:
            - name: data
              mountPath: /data
          envFrom:
            - configMapRef:
                name: mc
          resources:
            requests:
              memory: "4500Mi"
              cpu: "2000m"
            limits:
              memory: "4500Mi"
              cpu: "2000m"
          startupProbe:
            tcpSocket:
              port: 25565
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 25565
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
            successThreshold: 1
            timeoutSeconds: 1
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "pd-ssd"
        resources:
          requests:
            storage: 10Gi
